### ISSUE TITLE
Broken link https://(www.)bio7.org

### ISSUE THREAD

**Issue by DerAndere1** [Bio7/bio7#10]
Visits to `https://bio7.org` are redirected to an unrelated third-party website, at least when using the mozilla firefox browser. This affects the link in the sentence 

> A new release of Bio7 is available. 

in release notes of bio7 3.1 (https://bio7.org/bio7-3-1-released/) and possibly other places. Links to subpages (e.g. https://bio7.org/index) are not affected. Can be fixed by changing `https://bio7.org` to `https://www.bio7.org`.

**Comment by Bio7** [comment]
Thank you for the information. I corrected the link. `http://https//bio7.org` to the correct
`http://bio7.org `

**Comment by Bio7** [comment]
Can be closed.
