### ISSUE TITLE
[FR] Install modeling plugins by default

### ISSUE THREAD

**Issue by DerAndere1** [Bio7/bio7#11]
It would be nice to have some modeling tools installed by default. Since publication of [sbml2modelica](https://bitbucket.org/mclab/sbml2modelica/src/master/), see [Maggioli F, Mancini T, Tronci E. 2020](https://doi.org/10.1093/bioinformatics/btz860), Modelica becomes increasingly interesting for modeling. OpenModelica already provides the Eclipse plugins ["Modelica Development Tools" (MDT)](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/mdt.html) and [ModelicaML](https://www.openmodelica.org/?id=139:modelicaml) for graphical modeling using SysML notation.

**Comment by Bio7** [comment]
If they offer an Eclipse plugin you should be able to install it easily with the Update Manager.
However, shipping by default would increase the download size and the maintenance costs.
I already saw many plugins come and go (The start of development of Bio7 was 2004).

A while ago I made some suggestions for add-ons which fits quite well into Bio7, see:

https://www.r-bloggers.com/install-useful-eclipse-plugins-in-bio7-for-r-data-science-and-programming/

I can highly recommend the TM-Terminal, DBWeaver, Remote System Explorer, WindowBuilder, etc.
With the TM-Terminal and Remote Systems Explorer it is really fun to manage a server and edit files from within Bio7 with the available editors.

In addition there are some good ImageJ and R plugins to extend the Bio7 functionality to infinity.
You might find the same functions as an R package.
