### ISSUE TITLE
Can't find Bio7.ini file

### ISSUE THREAD

**Issue by LifeWorks** [Bio7/bio7#3]
I installed Bio7 2.5 on Mac but can not find Bio7.ini.

I want to increase the memory limit.

**Comment by Bio7** [comment]
You can find the information in the Bio7 User Guide here:

http://bio7.org/documentation/Main.html#toc-Subsection-2.1.11

For an increased Java heap space on MacOSX open the Bio7 package (context menu if you click on the icon) then go to Contents/MacOSX. In that folder you will find the Bio7.ini file!

**Comment by LifeWorks** [comment]
From the application that I download from the official site, there is no Bio7.ini file.

**Comment by Bio7** [comment]
If you install the Mac application with the *.dmg, e.g., from here:

https://sourceforge.net/projects/bio7/

You will install a typical Mac application in your software folder.

Now right click on the Bio7.app to show the package contens, similar to this description:

https://stackoverflow.com/questions/15454889/eclipse-ini-file-not-present-on-mac

There you can find and change the *.ini file

**Comment by LifeWorks** [comment]
As I said, I did exactly as you described. There is no .ini file in that folder. However, I found two Bio7.ini files in Contents/Eclipse and Contents/Eclipse/plugins/com.eco.bio7_2.5.0

**Comment by Bio7** [comment]
Yes, right. The Contents/Eclipse *.ini file is the file you have to customize. I just checked it on a MacOSX installation.

Open the file with, e.g., TextEdit and then change the following default values:

-Xms1024m
-Xmx4096m

**Comment by LifeWorks** [comment]
Thanks.
