### ISSUE TITLE
Bioformats integration

### ISSUE THREAD

**Issue by J-McNamara** [Bio7/bio7#8]
I have not been able to figure out how to get the Bioformats importer plugin running in Bio7.

**Comment by Bio7** [comment]
Just like in ImageJ.
Download the Bioformats plugin:
https://www.openmicroscopy.org/bio-formats/downloads/
Copy it in the ImageJ plugins location of Bio7. 
You can open the location with the menu:
**File->Show Folder->plugins**
This location can be changed in the Bio7 preferences:
**Preferences->Preferences ImageJ->Plugins Path**
The menus and ImageJ plugins can be updated with the menu action:
**Help->Refresh Menus**
Or you simply restart Bio7. 
The installed plugins actions extend the plugins view menu dynamically as in ImageJ.

Please note: If you have already an ImageJ installation with plugins you can simply point the Bio7 ImageJ plugins path to the plugins path of your ImageJ installation.

**Comment by J-McNamara** [comment]
Thanks very much. I should clarify- I am able to install and run plugins just as in my standard Fiji installation. But when I run the Bioformats plugin in a Bio7 ImageJ Edit window, nothing happens. Other plugins produce their standard dialog boxes.

PS- does Bio7 support ImageJ update sites?

**Comment by Bio7** [comment]
Bio7 uses ImageJ1 which FIJI also uses (same GUI). Please note that ImageJ1 is actively developed by Wayne Rasband.
ImageJ plugins or macros are installed within Bio7 the ImageJ1 way. Just put the *.class or *.jar plugins to the plugins location or use the script and ImageJ macros.

FIJI comes with it's own update sites. Bio7 doesn't support the FIJI update sites.

_But when I run the Bioformats plugin in a Bio7 ImageJ Edit window, nothing happens. Other plugins produce their standard dialog boxes._

I must admit that I don't understand. If the Bioformats plugin is installed the File (File->Imports->Bio-Formats) and the plugin menu can be used to import images with the Bioformats GUI. Or do you execute ImageJ macro code? Please note that FIJI adds some macro annotations to produce a GUI which is not ImageJ1 compatible.

Bio7 has it's own powerful Eclipse ImageJ macro editor and other scripting languages can be used, too, with Eclipse editors (Groovy, BeanShell, JavaScript, Jython), see:

https://www.youtube.com/watch?v=TqbnFnazxyw

https://www.youtube.com/watch?v=-kySAN9doXQ

More videos:

https://www.youtube.com/watch?v=-kySAN9doXQ

By the way it is possible to extend Bio7 with ImageJ2 classes but that would'nt bring you the FIJI specific functionality.
