### ISSUE TITLE
Dark theme under Windows 10: Some fonts remain black making them unreadable 

### ISSUE THREAD

**Issue by DerAndere1** [Bio7/bio7#9]
Minor issue: Whith dark theme under Windows 10, the following fonts remain black which makes them almost unreadable on the dark background: 
A) Text labels of buttons for changing between "perspectives"
B) Text labes "Console" and Options" in the toolbar of the console view.
C) Menu labels in the views "ImageJ-Canvas" and "Table"  
D) non-highlighted code in .R files when viewed with the R editor
E) Text inside the Console
F) (With "Git integration plugin for Eclipse" (Egit)): Names of projects and subfolders that contain changes that have not been pushed.

**Reproducible:** Always on my system

**Steps to reproduce:**
1. Go to Preferences -> General -> Appearance. 
2. Select Theme: "Dark" or "Dark [Linux]"
3.  Select Color and font theme: "default" or "classic" or "reduced palette".
4. Click "Apply and close"
5. Restart Bio 7

**Expected Result:**
All GUI elements and fonts should be adjusted to be readable on dark background automatically. 

**Actual observation:**
The font colors listed above stay black while other font colors get adjusted. 

**Partial work around:**
Manually change font colors for editors and consoles. This only solves D) and E),

**Comment by Bio7** [comment]
No workaround necessary. I think I mentioned it somewhere.
To apply the dark theme correctly please use the main menu action **Windows->Switch Theme**.
This switches to the Bio7 dark theme or back to the Bio7 "Light" theme and more important it changes the font colors of all Bio7 custom editors.

As you already found out the default theme switch of Eclipse only applies font colors, e.g., to the JDT Java editor. That's why I integrated a default action for Bio7.

You can also apply a script to change font colors to all Bio7 custom editors, see:

https://github.com/Bio7/bio7_examples/blob/master/Bio7_Java_Examples/src/extra/ChangeFontColors.java

**Comment by DerAndere1** [comment]
Thanks for the hints. Windows -> "Switch Theme" changes R editor font color (D) and the project name colors (F). The remaining issues A, B, C, (E) alre really not a big problem because these are only few static GUI elements that can be memorized by the people who whish to use the dark theme. Thank you for the great work on Bio7.

**Comment by Bio7** [comment]
After restart the text labels in A,B,C,E should also be white on black background.
Maybe you have to reset the preferences and then switch the theme?

**Comment by Bio7** [comment]
It should look like in the screenshots:

https://bio7.org/screenshots/

**Comment by DerAndere1** [comment]
It does not change those in my setup. What I did: 
1. Preferences -> General -> Appearance -> Reset Default -> Apply and close
2. Restart Bio7
3.  Windows -> Switch Theme
4. Restart

Now I tried disabling "Use themes" (or similar) and Bio7 doesnt not show the GUI anymore but runs in the background. Well I am sure a reinstall or deletion of some temporary file will solve my issues.

**Comment by Bio7** [comment]
You can delete the preferences and start Bio7 again if you delete the .metadata folder in your Bio7 workspace folder. The folder where all Bio7 projects are stored. 

Before  you can delete the folder kill the OpenJDK and Bio7 related processes. 

When you startup Bio7 again you have to reimport existing projects from the same folder!
Please don't deselect the "Enable Themes" option.

**Comment by DerAndere1** [comment]
Sure, I was a bit adventureous with that last setting. All Issues are solved now. I have the same dark theme look as on the screenshot. ImageJ-canvas view, 2d perspective and "tables" view are all readable now. Thanks.

**Comment by Bio7** [comment]
Good to hear. 

The "Enable Themes" Eclipse option is a bit unfortunate and unnecessary.

If you want to have it a little bit darker use the fullscreen action to blend out the menus and frame (the extra option hide menus is sometimes necessary if you switch to other editors (JDT) which adds some menus).
